//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_Yonetim_Form
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aidatlar
    {
        public int id { get; set; }
        public int ev { get; set; }
        public Nullable<decimal> odenmemis_aidat { get; set; }
        public System.DateTime odeme_tarihi { get; set; }
    
        public virtual Evler Evler { get; set; }
    }
}
