//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_Yonetim_Form
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evler()
        {
            this.Aidatlars = new HashSet<Aidatlar>();
        }
    
        public int id { get; set; }
        public byte numara { get; set; }
        public int sahibi { get; set; }
        public Nullable<int> kiracı { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aidatlar> Aidatlars { get; set; }
        public virtual Site_Sakinleri Site_Sakinleri { get; set; }
        public virtual Site_Sakinleri Site_Sakinleri1 { get; set; }
        public virtual Kiracilar Kiracilar { get; set; }
    }
}
