//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_Yonetim_Form
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Golpinar_Sitesi_Entities : DbContext
    {
        public Golpinar_Sitesi_Entities()
            : base("name=Golpinar_Sitesi_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Evler> Evlers { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
        public virtual DbSet<Site_Sakinleri> Site_Sakinleri { get; set; }
        public virtual DbSet<Aidatlar> Aidatlars { get; set; }
        public virtual DbSet<Harcama_Detay> Harcama_Detay { get; set; }
        public virtual DbSet<Harcamalar> Harcamalars { get; set; }
        public virtual DbSet<Kiracilar> Kiracilars { get; set; }
    }
}
