//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_Yonetim_Form
{
    using System;
    using System.Collections.Generic;
    
    public partial class Harcama_Detay
    {
        public int id { get; set; }
        public int harcama_id { get; set; }
        public string aciklama { get; set; }
        public decimal harcama { get; set; }
    
        public virtual Harcamalar Harcamalar { get; set; }
    }
}
