//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_Yonetim_Form
{
    using System;
    using System.Collections.Generic;
    
    public partial class Harcamalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Harcamalar()
        {
            this.Harcama_Detay = new HashSet<Harcama_Detay>();
        }
    
        public int id { get; set; }
        public System.DateTime tarih { get; set; }
        public Nullable<decimal> toplam_harcama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Harcama_Detay> Harcama_Detay { get; set; }
    }
}
